### ISSUE TITLE
Instance loss:0.00000 

### ISSUE THREAD

**Issue by mengpengfei** [klintan/pytorch-lanenet#16]
Epoch 3 Step 30 |(30/30)| ETA: 1.27|Total loss:0.87450|Binary loss:0.87450|Instance loss:0.00000|IoU:0.50841

why Instance loss is 0？is it a issue?

**Comment by mengpengfei** [comment]
![image](https://user-images.githubusercontent.com/13211758/113136992-920b7800-9256-11eb-8259-1171c34725bc.png)

**Comment by MrFlyer** [comment]
好兄弟你有没有遇到
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
这个问题麻烦请教下是怎么解决的

**Comment by ayushmankumar7** [comment]
Good brother, have you met
IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
Please tell me how to solve this problem

**Comment by MrFlyer** [comment]
YEAH I have met it and it also make me headache XD



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ayushman ***@***.***&gt;; 
发送时间: 2021年4月22日(星期四) 中午12:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [klintan/pytorch-lanenet] Instance loss:0.00000  (#16)





 
Good brother, have you met
 IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)
 Please tell me how to solve this problem

**Comment by klintan** [comment]
I think it's because of this latest commit. I'll try to revert back. I didn't double check it, and it was said to be in the paper 

https://github.com/klintan/pytorch-lanenet/commit/db9f116ba3f42dbfabf064e4a89ec068e9da4ee4

so if you change that back to what it was it should not fail. However I'll have to dig into the paper again to see what the main issue might be.

**Comment by ayushmankumar7** [comment]
Thank you so much @klintan !
